server:
  port: 8089
spring:
  application:
    name: use-discovery
  main:
    allow-beaan-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: f0f2ef4d-ef19-481d-ab05-501dc330e78f
        group: use-discovery
dubbo:
  scan:
    base-packages: com.github.lastsunday.cloud
  protocol:
    name: dubbo
    port: -1